CREATE DATABASE IF NOT EXISTS PERSONAL;
USE PERSONAL;

CREATE TABLE AREA (
    IDAREA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE ZONA (
    IDZONA INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE PUESTO (
    IDPUESTO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE ALUMNOS (
    LOGIN INT PRIMARY KEY,
    AREA INT,
    ZONA INT,
    PUESTO INT,
    NOMBRE VARCHAR(100) NOT NULL,
    UNIQUE (LOGIN),
    FOREIGN KEY (AREA) REFERENCES AREA(IDAREA),
    FOREIGN KEY (ZONA) REFERENCES ZONA(IDZONA),
    FOREIGN KEY (PUESTO) REFERENCES PUESTO(IDPUESTO)
);

INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5654', '1', '1', '1', 'EDGAR');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5652', '1', '1', '2', 'CESAR');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5650', '1', '2', '2', 'URIEL');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5648', '1', '3', '2', 'ISRAEL');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5646', '3', '1', '1', 'JOSUE');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5644', '3', '4', '2', 'FELIPE');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5642', '2', '2', '1', 'GUILLERMO');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5640', '2', '3', '2', 'ALI');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5638', '4', '1', '1', 'MAURO');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5636', '4', '4', '2', 'MIRIAM');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5634', '5', '2', '2', 'RICARDO');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5632', '5', '2', '1', 'LUIS');
INSERT INTO `personal`.`alumnos` (`LOGIN`, `AREA`, `ZONA`, `PUESTO`, `NOMBRE`) VALUES ('5630', '5', '3', '2', 'JOSE');







