#3.1 Mostrar a todos los coordinadores
SELECT A.* 
FROM ALUMNOS A
INNER JOIN PUESTO P ON A.PUESTO = P.IDPUESTO
WHERE P.DESCRIPCION = 'COORDINADOR';

#3.2 Personas que laboran en la zona Valle
SELECT A.* 
FROM ALUMNOS A
JOIN ZONA Z ON A.ZONA = Z.IDZONA
WHERE Z.DESCRIPCION LIKE "%VALLE%";

#3.3 Personas que laboran en la zona Narvarte
SELECT A.* 
FROM ALUMNOS A
JOIN ZONA Z ON A.ZONA = Z.IDZONA
WHERE Z.DESCRIPCION = 'NARVARTE';

#3.4 Agrupar todas las personas por Área
SELECT AR.DESCRIPCION AS AREA, A.NOMBRE
FROM ALUMNOS A
JOIN AREA AR ON A.AREA = AR.IDAREA
GROUP BY AR.DESCRIPCION, A.NOMBRE;


#3.5 cruce de resultados
Select AL.NOMBRE, AL.LOGIN, AR.DESCRIPCION AS AREA, Z.DESCRIPCION AS ZONA, P.DESCRIPCION AS PUESTO
FROM ALUMNOS AL 
INNER JOIN AREA AR ON AL.AREA = AR.IDAREA
INNER JOIN ZONA Z ON AL.ZONA = Z.IDZONA
INNER JOIN PUESTO P ON AL.PUESTO = P.IDPUESTO;

CALL SP_PERSONAS_POR_ZONA(2);

CALL SP_PERSONAS_POR_PUESTO(1);

call SP_PERSONAS_POR_AREA();

DELIMITER $$

CREATE PROCEDURE SP_PERSONAS_POR_ZONA(IN IDZONA_IN INT)
BEGIN
    SELECT A.* 
    FROM ALUMNOS A
    WHERE A.ZONA = IDZONA_IN;
END$$

DELIMITER ;

DELIMITER $$

CREATE PROCEDURE SP_PERSONAS_POR_PUESTO(IN PUESTO_IN INT)
BEGIN
    SELECT A.*
    FROM ALUMNOS A
    WHERE A.PUESTO = PUESTO_IN;
END$$

DELIMITER ;

DELIMITER $$
CREATE PROCEDURE SP_PERSONAS_POR_AREA()
BEGIN
	SELECT AR.DESCRIPCION AS AREA, COUNT(*) AS TOTAL_PERSONAS
	FROM ALUMNOS A
	JOIN AREA AR ON A.AREA = AR.IDAREA
	GROUP BY AR.DESCRIPCION;
END$$

DELIMITER ;


